---

- import_tasks: install.yml
  tags:
    - install_kafka

- import_tasks: create-topics.yml
  tags:
    - create_topics

- import_tasks: delete_topics.yml
  when: kafka_topics_delete | length > 0
  tags:
    - kafka_topics_delete
